title: Kelvin Chan
url: "https://kelvinchanwh.com"
# baseurl: "https://kelvinchanwh.com"

markdown: kramdown
ins_logo: "./kelvinchanwh-logo-clear.png"
favicon: "./kelvinchanwh-logo-filled.png"

tracking_id: #

footer: yes
footer_url: "https://linkedin.com/in/kelvinchanwh"
footer_text: "Kelvin Chan. "

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Projects"
   link: "#projects"
 - name: "Resume"
   link: "Kelvin_Chan_CV.pdf"
 - name: "Contact"
   link: "#contact"

plugins: ["jekyll-include-cache"]